# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openscout.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='openscout.proto',
  package='openscout',
  syntax='proto3',
  serialized_pb=_b('\n\x0fopenscout.proto\x12\topenscout\"+\n\x06\x45xtras\x12\x13\n\x0bis_training\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\tB\x1e\n\x14\x65\x64u.cmu.cs.openscoutB\x06Protosb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EXTRAS = _descriptor.Descriptor(
  name='Extras',
  full_name='openscout.Extras',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_training', full_name='openscout.Extras.is_training', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='openscout.Extras.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['Extras'] = _EXTRAS

Extras = _reflection.GeneratedProtocolMessageType('Extras', (_message.Message,), dict(
  DESCRIPTOR = _EXTRAS,
  __module__ = 'openscout_pb2'
  # @@protoc_insertion_point(class_scope:openscout.Extras)
  ))
_sym_db.RegisterMessage(Extras)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024edu.cmu.cs.openscoutB\006Protos'))
# @@protoc_insertion_point(module_scope)
