apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearchservice.name }}
  labels:
    app: {{ template "openscout.name" . }}
    chart: {{ template "openscout.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.elasticsearchservice.type }}
  selector:
    app: {{ .Values.elasticsearchservice.name }}
    release: {{ .Release.Name }}
  ports:
    - name: {{ .Values.elasticsearchservice.name }}
      port: {{ .Values.elasticsearchservice.port }}
