"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Location(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    name: builtins.str
    latitude: builtins.float
    longitude: builtins.float
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        latitude: builtins.float = ...,
        longitude: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["latitude", b"latitude", "longitude", b"longitude", "name", b"name"]) -> None: ...

global___Location = Location

@typing_extensions.final
class Extras(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_TRAINING_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    is_training: builtins.bool
    name: builtins.str
    client_id: builtins.str
    @property
    def location(self) -> global___Location: ...
    model: builtins.str
    def __init__(
        self,
        *,
        is_training: builtins.bool = ...,
        name: builtins.str = ...,
        client_id: builtins.str = ...,
        location: global___Location | None = ...,
        model: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["location", b"location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["client_id", b"client_id", "is_training", b"is_training", "location", b"location", "model", b"model", "name", b"name"]) -> None: ...

global___Extras = Extras
