apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.httpdservice.name }}
  labels:
    app: {{ template "openscout.name" . }}
    chart: {{ template "openscout.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.httpdservice.type }}
  selector:
    app: {{ template "openscout.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: port
      port: {{ .Values.httpdservice.port  }}
{{ if eq .Values.httpdservice.type "NodePort"}}
      targetPort: {{ .Values.httpdservice.port }}
      nodePort: {{ .Values.httpdservice.nodePort }}
{{ end }}
