apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.images.httpd.name }}
  labels:
    app: {{ .Values.images.httpd.name }}
    chart: {{ .Values.images.httpd.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.images.httpd.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.images.httpd.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.images.httpd.name }}
          image: "{{ .Values.images.httpd.repository }}:{{ .Values.images.httpd.tag }}"
          imagePullPolicy: {{ .Values.images.openscout.pullPolicy }}
          ports:
            - containerPort: {{ .Values.images.httpd.port }}
              hostPort: {{ .Values.images.httpd.nodePort }}
              protocol: {{ .Values.deployment.protocol }}
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/openscout
      volumes:
        - name: shared-data
          emptyDir: {}
